In [71]:
import pandas as pd

In [72]:
df=pd.read_csv("../IMDB Dataset.csv")
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

Lowercaseing

In [73]:
df['review']=df['review'].str.lower()
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. <br /><br />the...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

Another way to lowercase

In [74]:
def covert_lower(text):
    return text.lower()

In [75]:
df['review']=df['review'].apply(covert_lower)
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. <br /><br />the...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

REMOVE HTML TAGS

In [76]:
import re
def remove_html_tags(text):
    clean = re.compile('<.*?>')
    return re.sub(clean, '', text)

In [77]:
df['review']=df['review'].apply(remove_html_tags)
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. the filming tec...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

URL REMOVE

In [78]:
def remove_url(text):
    pattern=re.compile(r'https?://\S+|www\.\S+')
    return re.sub(pattern,'',text)

In [79]:
text1 = 'Check out my notebook https://www.kaggle.com/campusx/notebook8223fc1abb'
text2 = 'Check out my notebook http://www.kaggle.com/campusx/notebook8223fc1abb'
text3 = 'Google search here www.google.com'
text4 = 'For notebook click https://www.kaggle.com/campusx/notebook8223fc1abb to search check www.google.com'

In [80]:
print(remove_url(text1))
print(remove_url(text2))
print(remove_url(text3))
print(remove_url(text4))

Check out my notebook
Check out my notebook
Google search here
For notebook click  to search check

REMOVE PUNCTUATIONS

In [81]:
import string
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [82]:
exclude=string.punctuation

In [83]:
def remove_punc(text):
    return text.translate(str.maketrans('','',exclude))

Note: maketrans(Characters to replace, Characters to replace them with, Characters to delete)
'': no character to replace
'': no character to replace with
punc_list: characters to delete from the text

In [84]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. the filming tec...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

In [85]:
text="Hello!!!, How are you doing? @#"
remove_punc(text) #when a string is passed to the function it will remove all the punctuation from the string and return only the words
#print(df['review'].apply(remove_punc)) #when we apply the function to a specific column it will remove all the punctuation from the review column and return only the words

'Hello How are you doing '

In [86]:
from textblob import TextBlob

In [87]:
incorect_spelling = "I havv goood speling"
corrected_text = TextBlob(incorect_spelling).correct()
print(corrected_text)

another_incorect_spelling = "I hava veey goood speling"
corrected_text2 = TextBlob(another_incorect_spelling).correct()
print(corrected_text2)

I have good spelling
I have very good spelling

STOP WORDS REMOVE

In [88]:
import nltk
from nltk.corpus import stopwords

In [89]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [90]:
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [91]:
stopwords.words('bengali')

['অতএব',
 'অথচ',
 'অথবা',
 'অনুযায়ী',
 'অনেক',
 'অনেকে',
 'অনেকেই',
 'অন্তত',
 'অন্য',
 'অবধি',
 'অবশ্য',
 'অর্থাত',
 'আই',
 'আগামী',
 'আগে',
 'আগেই',
 'আছে',
 'আজ',
 'আদ্যভাগে',
 'আপনার',
 'আপনি',
 'আবার',
 'আমরা',
 'আমাকে',
 'আমাদের',
 'আমার',
 'আমি',
 'আর',
 'আরও',
 'ই',
 'ইত্যাদি',
 'ইহা',
 'উচিত',
 'উত্তর',
 'উনি',
 'উপর',
 'উপরে',
 'এ',
 'এঁদের',
 'এঁরা',
 'এই',
 'একই',
 'একটি',
 'একবার',
 'একে',
 'এক্',
 'এখন',
 'এখনও',
 'এখানে',
 'এখানেই',
 'এটা',
 'এটাই',
 'এটি',
 'এত',
 'এতটাই',
 'এতে',
 'এদের',
 'এব',
 'এবং',
 'এবার',
 'এমন',
 'এমনকী',
 'এমনি',
 'এর',
 'এরা',
 'এল',
 'এস',
 'এসে',
 'ঐ',
 'ও',
 'ওঁদের',
 'ওঁর',
 'ওঁরা',
 'ওই',
 'ওকে',
 'ওখানে',
 'ওদের',
 'ওর',
 'ওরা',
 'কখনও',
 'কত',
 'কবে',
 'কমনে',
 'কয়েক',
 'কয়েকটি',
 'করছে',
 'করছেন',
 'করতে',
 'করবে',
 'করবেন',
 'করলে',
 'করলেন',
 'করা',
 'করাই',
 'করায়',
 'করার',
 'করি',
 'করিতে',
 'করিয়া',
 'করিয়ে',
 'করে',
 'করেই',
 'করেছিলেন',
 'করেছে',
 'করেছেন',
 'করেন',
 'কাউকে',
 'কাছ',
 'কাছে',
 'কাজ',
 'কাজে',
 'কারও',
 'কারণ',
 'কি',
 'কিংবা',
 'কিছু',
 'কিছুই',
 'কিন্তু',
 'কী',
 'কে',
 'কেউ',
 'কেউই',
 'কেখা',
 'কেন',
 'কোটি',
 'কোন',
 'কোনও',
 'কোনো',
 'ক্ষেত্রে',
 'কয়েক',
 'খুব',
 'গিয়ে',
 'গিয়েছে',
 'গিয়ে',
 'গুলি',
 'গেছে',
 'গেল',
 'গেলে',
 'গোটা',
 'চলে',
 'চান',
 'চায়',
 'চার',
 'চালু',
 'চেয়ে',
 'চেষ্টা',
 'ছাড়া',
 'ছাড়াও',
 'ছিল',
 'ছিলেন',
 'জন',
 'জনকে',
 'জনের',
 'জন্য',
 'জন্যওজে',
 'জানতে',
 'জানা',
 'জানানো',
 'জানায়',
 'জানিয়ে',
 'জানিয়েছে',
 'জে',
 'জ্নজন',
 'টি',
 'ঠিক',
 'তখন',
 'তত',
 'তথা',
 'তবু',
 'তবে',
 'তা',
 'তাঁকে',
 'তাঁদের',
 'তাঁর',
 'তাঁরা',
 'তাঁাহারা',
 'তাই',
 'তাও',
 'তাকে',
 'তাতে',
 'তাদের',
 'তার',
 'তারপর',
 'তারা',
 'তারৈ',
 'তাহলে',
 'তাহা',
 'তাহাতে',
 'তাহার',
 'তিনঐ',
 'তিনি',
 'তিনিও',
 'তুমি',
 'তুলে',
 'তেমন',
 'তো',
 'তোমার',
 'থাকবে',
 'থাকবেন',
 'থাকা',
 'থাকায়',
 'থাকে',
 'থাকেন',
 'থেকে',
 'থেকেই',
 'থেকেও',
 'দিকে',
 'দিতে',
 'দিন',
 'দিয়ে',
 'দিয়েছে',
 'দিয়েছেন',
 'দিলেন',
 'দু',
 'দুই',
 'দুটি',
 'দুটো',
 'দেওয়া',
 'দেওয়ার',
 'দেওয়া',
 'দেখতে',
 'দেখা',
 'দেখে',
 'দেন',
 'দেয়',
 'দ্বারা',
 'ধরা',
 'ধরে',
 'ধামার',
 'নতুন',
 'নয়',
 'না',
 'নাই',
 'নাকি',
 'নাগাদ',
 'নানা',
 'নিজে',
 'নিজেই',
 'নিজেদের',
 'নিজের',
 'নিতে',
 'নিয়ে',
 'নিয়ে',
 'নেই',
 'নেওয়া',
 'নেওয়ার',
 'নেওয়া',
 'নয়',
 'পক্ষে',
 'পর',
 'পরে',
 'পরেই',
 'পরেও',
 'পর্যন্ত',
 'পাওয়া',
 'পাচ',
 'পারি',
 'পারে',
 'পারেন',
 'পি',
 'পেয়ে',
 'পেয়্র্',
 'প্রতি',
 'প্রথম',
 'প্রভৃতি',
 'প্রযন্ত',
 'প্রাথমিক',
 'প্রায়',
 'প্রায়',
 'ফলে',
 'ফিরে',
 'ফের',
 'বক্তব্য',
 'বদলে',
 'বন',
 'বরং',
 'বলতে',
 'বলল',
 'বললেন',
 'বলা',
 'বলে',
 'বলেছেন',
 'বলেন',
 'বসে',
 'বহু',
 'বা',
 'বাদে',
 'বার',
 'বি',
 'বিনা',
 'বিভিন্ন',
 'বিশেষ',
 'বিষয়টি',
 'বেশ',
 'বেশি',
 'ব্যবহার',
 'ব্যাপারে',
 'ভাবে',
 'ভাবেই',
 'মতো',
 'মতোই',
 'মধ্যভাগে',
 'মধ্যে',
 'মধ্যেই',
 'মধ্যেও',
 'মনে',
 'মাত্র',
 'মাধ্যমে',
 'মোট',
 'মোটেই',
 'যখন',
 'যত',
 'যতটা',
 'যথেষ্ট',
 'যদি',
 'যদিও',
 'যা',
 'যাঁর',
 'যাঁরা',
 'যাওয়া',
 'যাওয়ার',
 'যাওয়া',
 'যাকে',
 'যাচ্ছে',
 'যাতে',
 'যাদের',
 'যান',
 'যাবে',
 'যায়',
 'যার',
 'যারা',
 'যিনি',
 'যে',
 'যেখানে',
 'যেতে',
 'যেন',
 'যেমন',
 'র',
 'রকম',
 'রয়েছে',
 'রাখা',
 'রেখে',
 'লক্ষ',
 'শুধু',
 'শুরু',
 'সঙ্গে',
 'সঙ্গেও',
 'সব',
 'সবার',
 'সমস্ত',
 'সম্প্রতি',
 'সহ',
 'সহিত',
 'সাধারণ',
 'সামনে',
 'সি',
 'সুতরাং',
 'সে',
 'সেই',
 'সেখান',
 'সেখানে',
 'সেটা',
 'সেটাই',
 'সেটাও',
 'সেটি',
 'স্পষ্ট',
 'স্বয়ং',
 'হইতে',
 'হইবে',
 'হইয়া',
 'হওয়া',
 'হওয়ায়',
 'হওয়ার',
 'হচ্ছে',
 'হত',
 'হতে',
 'হতেই',
 'হন',
 'হবে',
 'হবেন',
 'হয়',
 'হয়তো',
 'হয়নি',
 'হয়ে',
 'হয়েই',
 'হয়েছিল',
 'হয়েছে',
 'হয়েছেন',
 'হল',
 'হলে',
 'হলেই',
 'হলেও',
 'হলো',
 'হাজার',
 'হিসাবে',
 'হৈলে',
 'হোক',
 'হয়']

In [92]:
def stop_words(text):
    new_text=[]
    stop_words=set(stopwords.words('english'))
    for word in text.split():
        if word in stop_words:
            new_text.append('')
        else:
            new_text.append(word)
        
    return " ".join(new_text)

In [93]:
stop_words("Basics Steps Examples.ipynb is a notebook which contains the basic steps of text preprocessing in NLP")

'Basics Steps Examples.ipynb   notebook  contains  basic steps  text preprocessing  NLP'

In [94]:
df['review']=df['review'].apply(stop_words)
df.head()

                                              review sentiment
0  one    reviewers  mentioned   watching  1 oz e...  positive
1   wonderful little production.  filming techniq...  positive
2   thought    wonderful way  spend time    hot s...  positive
3  basically there's  family   little boy (jake) ...  negative
4  petter mattei's "love   time  money"   visuall...  positive

In [96]:
def remove_extra_space(text):
    return " ".join(text.split())
df['review']=df['review'].apply(remove_extra_space)
df.head()

                                              review sentiment
0  one reviewers mentioned watching 1 oz episode ...  positive
1  wonderful little production. filming technique...  positive
2  thought wonderful way spend time hot summer we...  positive
3  basically there's family little boy (jake) thi...  negative
4  petter mattei's "love time money" visually stu...  positive

REMOVE EMOJI

In [101]:
import re
def remove_emoji(text):
    emoji_pattern = re.compile("["
                           u"\U0001F600-\U0001F64F"  # emoticons
                           u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                           u"\U0001F680-\U0001F6FF"  # transport & map symbols
                           u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                           u"\U00002702-\U000027B0"
                           u"\U000024C2-\U0001F251"
                           "]+", flags=re.UNICODE)
    return emoji_pattern.sub(r'', text)

In [102]:
remove_emoji("Loved the movie. It was 😘😘")

'Loved the movie. It was '

In [103]:
remove_emoji("Lmao 😂😂")

'Lmao '

In [109]:
import emoji
print(emoji.demojize('Python is 🔥'))
print(emoji.demojize('Loved the movie. It was 😘'))

Python is :fire:
Loved the movie. It was :face_blowing_a_kiss:

WORD TOKEN

In [110]:
#using split
text="Basics Steps Examples.ipynb is a notebook which contains the basic steps of text preprocessing in NLP"
text.split()

['Basics',
 'Steps',
 'Examples.ipynb',
 'is',
 'a',
 'notebook',
 'which',
 'contains',
 'the',
 'basic',
 'steps',
 'of',
 'text',
 'preprocessing',
 'in',
 'NLP']

In [111]:
#sentences
text="Basics Steps Examples.ipynb is a notebook which contains the basic steps of text preprocessingin NLP. It is a very useful notebook for beginners."
text.split('.')

['Basics Steps Examples',
 'ipynb is a notebook which contains the basic steps of text preprocessingin NLP',
 ' It is a very useful notebook for beginners',
 '']

In [113]:
#BY REGEX
import re
text="Basics Steps Examples.ipynb is a notebook which contains the basic steps of text preprocessingin NLP. It is a very useful notebook for beginners."
re.compile(r'[.?!]').split(text)

['Basics Steps Examples',
 'ipynb is a notebook which contains the basic steps of text preprocessingin NLP',
 ' It is a very useful notebook for beginners',
 '']

In [115]:
text="Basics Steps Examples.ipynb is a notebook which contains the basic steps of text preprocessingin NLP. It is a very useful notebook for beginners! Do you like it?"
re.findall('[\w]+', text)

['Basics',
 'Steps',
 'Examples',
 'ipynb',
 'is',
 'a',
 'notebook',
 'which',
 'contains',
 'the',
 'basic',
 'steps',
 'of',
 'text',
 'preprocessingin',
 'NLP',
 'It',
 'is',
 'a',
 'very',
 'useful',
 'notebook',
 'for',
 'beginners',
 'Do',
 'you',
 'like',
 'it']

In [123]:
#NLTK

import nltk
nltk.download('punkt_tab')
from nltk.tokenize import word_tokenize,sent_tokenize
text="Basics Steps Examples.ipynb is a notebook which contains the basic steps of text preprocessingin NLP. It is a very useful notebook for beginners! Do you like it?"
word_tokenize(text)

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.

['Basics',
 'Steps',
 'Examples.ipynb',
 'is',
 'a',
 'notebook',
 'which',
 'contains',
 'the',
 'basic',
 'steps',
 'of',
 'text',
 'preprocessingin',
 'NLP',
 '.',
 'It',
 'is',
 'a',
 'very',
 'useful',
 'notebook',
 'for',
 'beginners',
 '!',
 'Do',
 'you',
 'like',
 'it',
 '?']

In [134]:
import spacy
!python -m spacy download en_core_web_sm

Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
      --------------------------------------- 0.3/12.8 MB ? eta -:--:--
     --- ------------------------------------ 1.0/12.8 MB 5.0 MB/s eta 0:00:03
     ------ --------------------------------- 2.1/12.8 MB 4.7 MB/s eta 0:00:03
     ---------- ----------------------------- 3.4/12.8 MB 5.0 MB/s eta 0:00:02
     ------------ --------------------------- 3.9/12.8 MB 4.6 MB/s eta 0:00:02
     -------------- ------------------------- 4.7/12.8 MB 4.7 MB/s eta 0:00:02
     ------------------ --------------------- 5.8/12.8 MB 4.4 MB/s eta 0:00:02
     ------------------ --------------------- 6.0/12.8 MB 4.1 MB/s eta 0:00:02
     -------------------- ------------------- 6.6/12.8 MB 3.8 MB/s eta 0:00:02
     --------------------- ------------------ 6.8/12.8 MB 3.7 MB/s eta 0:00:02
     ---------------------- ----------------- 7.3/12.8 MB 3.5 MB/s eta 0:00:02
     ------------------------ --------------- 7.9/12.8 MB 3.3 MB/s eta 0:00:02
     ------------------------- -------------- 8.1/12.8 MB 3.3 MB/s eta 0:00:02
     --------------------------- ------------ 8.7/12.8 MB 3.2 MB/s eta 0:00:02
     ---------------------------- ----------- 9.2/12.8 MB 3.1 MB/s eta 0:00:02
     ------------------------------ --------- 9.7/12.8 MB 3.0 MB/s eta 0:00:02
     ------------------------------- -------- 10.0/12.8 MB 3.0 MB/s eta 0:00:01
     -------------------------------- ------- 10.5/12.8 MB 2.9 MB/s eta 0:00:01
     --------------------------------- ------ 10.7/12.8 MB 2.8 MB/s eta 0:00:01
     ---------------------------------- ----- 11.0/12.8 MB 2.8 MB/s eta 0:00:01
     ------------------------------------ --- 11.5/12.8 MB 2.7 MB/s eta 0:00:01
     ------------------------------------ --- 11.8/12.8 MB 2.7 MB/s eta 0:00:01
     ------------------------------------- -- 12.1/12.8 MB 2.7 MB/s eta 0:00:01
     ---------------------------------------  12.6/12.8 MB 2.6 MB/s eta 0:00:01
     ---------------------------------------- 12.8/12.8 MB 2.5 MB/s  0:00:05
Installing collected packages: en-core-web-sm
Successfully installed en-core-web-sm-3.8.0
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')

WARNING: Ignoring invalid distribution ~atplotlib (g:\ANACONDA\Lib\site-packages)
WARNING: Ignoring invalid distribution ~umpy (g:\ANACONDA\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (g:\ANACONDA\Lib\site-packages)
WARNING: Ignoring invalid distribution ~umpy (g:\ANACONDA\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (g:\ANACONDA\Lib\site-packages)
WARNING: Ignoring invalid distribution ~umpy (g:\ANACONDA\Lib\site-packages)

In [135]:
text="Basics Steps Examples.ipynb is a notebook which contains the basic steps of text preprocessingin NLP. It is a very useful notebook for beginners."
nlp=spacy.load('en_core_web_sm')
doc=nlp(text)
for token in doc:
    print(token)

Basics
Steps
Examples.ipynb
is
a
notebook
which
contains
the
basic
steps
of
text
preprocessingin
NLP
.
It
is
a
very
useful
notebook
for
beginners
.

STEMMING

In [136]:
from nltk.stem.porter import PorterStemmer

In [137]:
ps = PorterStemmer()
def stemming(text):
    stemmed_text=[]
    for word in text.split():
        stemmed_text.append(ps.stem(word))
    return " ".join(stemmed_text)

In [138]:
text="Basics Steps Examples.ipynb is a notebook which contains the basic steps of text preprocessingin NLP. It is a very useful notebook for beginners! Do you like it?"
stemming(text)

'basic step examples.ipynb is a notebook which contain the basic step of text preprocessingin nlp. it is a veri use notebook for beginners! do you like it?'

In [140]:
sample = "walk walks walking walked"
stemming(sample)

'walk walk walk walk'

In stemming the problem is while converting it in the root word it makes mistakes like make a word which not even exist solution is

LEMMATIZER

In [141]:
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Lenovo\AppData\Roaming\nltk_data...

True

In [146]:
lemma = WordNetLemmatizer()
punctuation = string.punctuation

def lemmatization(text):
    token=nltk.word_tokenize(text)
    for word in token:
        if word in punctuation:
            token.remove(word)
    print("{0:20}{1:20}".format("Word","Lemma"))
    for word in token:
        print("{0:20}{1:20}".format(word,lemma.lemmatize(word,pos='v')))

In [147]:
text="Basics running Steps Examples.ipynb is a notebook which contains the basic steps of text preprocessingin NLP. It is a very useful notebook for beginners! Do you like it?"
lemmatization(text)

Word                Lemma
Basics              Basics
running             run
Steps               Steps
Examples.ipynb      Examples.ipynb
is                  be
a                   a
notebook            notebook
which               which
contains            contain
the                 the
basic               basic
steps               step
of                  of
text                text
preprocessingin     preprocessingin
NLP                 NLP
It                  It
is                  be
a                   a
very                very
useful              useful
notebook            notebook
for                 for
beginners           beginners
Do                  Do
you                 you
like                like
it                  it

SHORT WORDS LEFT